/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

/**
 *
 * @author JuanJ
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Menu1 = new javax.swing.JPanel();
        jPMenu = new javax.swing.JPanel();
        jBAdministrativo = new javax.swing.JButton();
        jbDocente = new javax.swing.JButton();
        jBAlumno = new javax.swing.JButton();
        jPInteractuar = new javax.swing.JPanel();
        jPBienvenida = new javax.swing.JPanel();
        jlBienvenida = new javax.swing.JLabel();
        jPEstudiante = new javax.swing.JPanel();
        jPAdministrativo = new javax.swing.JPanel();
        jPDocente = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu1.setBackground(new java.awt.Color(51, 204, 255));
        Menu1.setLayout(new java.awt.BorderLayout());

        jPMenu.setBackground(new java.awt.Color(0, 153, 51));

        jBAdministrativo.setText("Administrativo");
        jBAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdministrativoActionPerformed(evt);
            }
        });
        jPMenu.add(jBAdministrativo);

        jbDocente.setText("Docente");
        jbDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDocenteActionPerformed(evt);
            }
        });
        jPMenu.add(jbDocente);

        jBAlumno.setText("Alumno");
        jBAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlumnoActionPerformed(evt);
            }
        });
        jPMenu.add(jBAlumno);

        Menu1.add(jPMenu, java.awt.BorderLayout.PAGE_START);

        jPInteractuar.setBackground(new java.awt.Color(0, 153, 153));
        jPInteractuar.setLayout(new java.awt.CardLayout());

        jPBienvenida.setBackground(new java.awt.Color(0, 153, 153));

        jlBienvenida.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBienvenida.setText("Bienvenido, en este momento se encuentra en el menu de selección de roles, donde podra elegir un rol");

        javax.swing.GroupLayout jPBienvenidaLayout = new javax.swing.GroupLayout(jPBienvenida);
        jPBienvenida.setLayout(jPBienvenidaLayout);
        jPBienvenidaLayout.setHorizontalGroup(
            jPBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBienvenidaLayout.setVerticalGroup(
            jPBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jPInteractuar.add(jPBienvenida, "card5");

        javax.swing.GroupLayout jPEstudianteLayout = new javax.swing.GroupLayout(jPEstudiante);
        jPEstudiante.setLayout(jPEstudianteLayout);
        jPEstudianteLayout.setHorizontalGroup(
            jPEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        jPEstudianteLayout.setVerticalGroup(
            jPEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jPInteractuar.add(jPEstudiante, "card4");

        javax.swing.GroupLayout jPAdministrativoLayout = new javax.swing.GroupLayout(jPAdministrativo);
        jPAdministrativo.setLayout(jPAdministrativoLayout);
        jPAdministrativoLayout.setHorizontalGroup(
            jPAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        jPAdministrativoLayout.setVerticalGroup(
            jPAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jPInteractuar.add(jPAdministrativo, "card3");

        javax.swing.GroupLayout jPDocenteLayout = new javax.swing.GroupLayout(jPDocente);
        jPDocente.setLayout(jPDocenteLayout);
        jPDocenteLayout.setHorizontalGroup(
            jPDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        jPDocenteLayout.setVerticalGroup(
            jPDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jPInteractuar.add(jPDocente, "card2");

        Menu1.add(jPInteractuar, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlumnoActionPerformed
        jPInteractuar.removeAll();
        jPInteractuar.add(jPEstudiante);
        jPInteractuar.repaint();
        jPInteractuar.revalidate();
    }//GEN-LAST:event_jBAlumnoActionPerformed

    private void jbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDocenteActionPerformed
        jPInteractuar.removeAll();
        jPInteractuar.add(jPDocente);
        jPInteractuar.repaint();
        jPInteractuar.revalidate();
    }//GEN-LAST:event_jbDocenteActionPerformed

    private void jBAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdministrativoActionPerformed
        jPInteractuar.removeAll();
        jPInteractuar.add(jPAdministrativo);
        jPInteractuar.repaint();
        jPInteractuar.revalidate();
    }//GEN-LAST:event_jBAdministrativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAdministrativo;
    private javax.swing.JButton jBAlumno;
    private javax.swing.JPanel jPAdministrativo;
    private javax.swing.JPanel jPBienvenida;
    private javax.swing.JPanel jPDocente;
    private javax.swing.JPanel jPEstudiante;
    private javax.swing.JPanel jPInteractuar;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JButton jbDocente;
    private javax.swing.JLabel jlBienvenida;
    // End of variables declaration//GEN-END:variables
}
